### ISSUE TITLE
Slow problem with a webcam

### ISSUE THREAD

**Issue by babou7635** [pibooth/pibooth#186] opened 2020-10-06 05:44 UTC
Hello,
I come back to you for a new question. When I run Pibooth with a webcam the preview is crazy (3 seconds between the real image and the preview). And the countdown is no longer displayed with numbers but with transparent rectangles.
While when I use the Camera of the raspberry (V2 black) there was no problem.

**Environment**
 - OS Raspbian
 - Camera Webcam papalook PA552
 - Pibooth version V2.0.0

**Comment by anxuae** [comment] 2020-10-06 15:31
Hi @babou7635 

Thanks for reporting. It is probably the same issue than #91. 
Your camera seems to have a very high resolution, and processing each frame takes time.

Code optimization may be done in the following method:

https://github.com/pibooth/pibooth/blob/2e538441ae4c129c44b4b17c9d7337700e39181e/pibooth/camera/opencv.py#L77-L102

But I have no such camera to do this work

**Comment by werdeil** [comment] 2020-10-14 14:40
Hi @babou7635,

About the transparent rectangle: can you tell us which version of Pillow you use (just write `pip show pillow` on a shell)

If it is version 7.2.0, try to downgrade to 7.1.2 (`pip install pillow=7.1.2`) and tell us if it solves at least the transparent rectangles.

About the slowness I'm trying to reproduce it, I had the same issue but I can't reproduce now, I need to understand why.

**Comment by werdeil** [comment] 2020-10-16 14:37
hi @babou7635, I've reproduce the slowness problem with my Logitech C920 and a Raspberry Pi 3B, and I pushed a PR (#193) that could a workaround on this.

**Comment by mmk8283** [comment] 2020-10-25 15:40
I am also having issues with the white transparent rectangles appearing instead of countdown numbers. This happens when using a webcam, if I use a pi camera the numbers appear correctly. I tried different versions of Pillow with no change. Any help on this issue would be appreciated 

Thank you!

**Comment by anxuae** [comment] 2020-11-14 09:28
Hi everybody,

The PR #193 is now merged, @babou7635 you can try if the preview is improved by installing a developing version of pibooth.

**Comment by anxuae** [comment] 2021-01-31 16:03
Since no news about this issue, I consider the fix PR #193 is solving it.
Please feel free to re-open this issue if it is not the case.

**Closed by anxuae** 2021-01-31 16:03 UTC
Labels: bug
